title: Katie Gerot
header-img: img/geometria.png
SEOTitle: "Katie Gerot"
description: "Writeups on statistics, programming, mathematics, and pedagogy (as well as whatever is interesting to me at the moment)."
url: "http://kgerot.github.io"
github_repo: "https://github.com/kgerot/kgerot.github.io"
featured-tags: True
featured-condition-size: 2
baseurl: ""
RSS: true
github_username: kgerot
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true
gems: [jekyll-paginate, jekyll-seo-tag]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
chrome-tab-theme-color: "#000000"
service-worker: true
