title: Katie Gerot
header-img: img/pixabay-burdock.jpg
url: "http://kgerot.github.io"
baseurl: ""
sidebar: true
sidebar-about-description: "Senior Computer Science and Math Major with a minor in Statistics at the University of Nebraska--Lincoln."
sidebar-avatar:  img/profile.jpg
RSS: true
github_username:  kgerot
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
chrome-tab-theme-color: "#000000"
service-worker: true